import { db, ensureAuth, ref, get, set, update, remove, onValue, runTransaction } from "./firebase.js";
import { bestTop10Match } from "./top10-match.js";
import { $, roomCodeFromUrl, qs, escapeHtml, now } from "./common.js";
const room=roomCodeFromUrl(), token=qs.get('token')||'';let user,meta,solutions=null,pending=null,pub=null;
const rr=p=>ref(db,`rooms/${room}${p?'/'+p:''}`);
async function boot(){if(!room||!token){$("hostStatus").textContent='رابط الحكم ناقص.';return;}user=await ensureAuth();$("hostRoom").textContent=room;const ms=await get(rr('meta'));if(!ms.exists()){$("hostStatus").textContent='الغرفة غير موجودة.';return;}meta=ms.val();if(meta.game!=='top10'||meta.variant!=='host'){$("hostStatus").textContent='هذه الغرفة ليست Top 10 بنظام الحكم.';return;}await set(rr(`hostJoin/${user.uid}`),{token,requestedAt:now()});$("hostStatus").textContent='تم إرسال طلب الربط…';onValue(rr('meta'),s=>{meta=s.val()||meta;if(meta.hostUid===user.uid){$("hostStatus").textContent='✅ تم ربط هذا الجهاز كحكم.';$("hostApp").classList.remove('hidden');start();}});}
function start(){onValue(rr('hostPrivate/current'),s=>{solutions=s.val();render()});onValue(rr('hostPending'),s=>{pending=s.val();render()});onValue(rr('public/top10'),s=>{pub=s.val();render()});}
function render(){if(!solutions||!pub){$("hostApp").innerHTML='<div class="panel"><div class="muted">بانتظار بدء السؤال من الشاشة العامة…</div></div>';return;}const revealed=pub.revealed||{};let suggestion='';if(pending?.text){const b=bestTop10Match(pending.text,solutions.answers,Object.keys(revealed).map(Number));suggestion=`<div class="suggestion"><div class="small">إجابة الفريق</div><b style="font-size:20px">${escapeHtml(pending.text)}</b>${b.index>=0?`<div class="small" style="margin-top:8px">أقرب تطابق مقترح</div><div style="font-size:20px;font-weight:900">#${b.index+1} — ${escapeHtml(solutions.answers[b.index])}</div><div class="small">تشابه ${b.score}%</div><div class="toolbar"><button class="primary" id="confirmSuggested" data-i="${b.index}">تأكيد وفتح المركز</button><button class="danger" id="wrongSuggested">رفض 💔</button></div>`:'<div class="notice">ما لقيت تطابق واضح. اختاري يدويًا من القائمة أو ارفضي.</div>'}</div>`;}
$("hostApp").innerHTML=`<div class="panel"><div class="small">الجولة ${pub.round||0}</div><h2>${escapeHtml(solutions.question||'')}</h2>${suggestion}<div class="answer-list">${solutions.answers.map((a,i)=>`<button class="host-solution ${revealed[i]!=null?'used':''}" data-i="${i}" ${revealed[i]!=null?'disabled':''}><span class="rank">${i+1}</span><b>${escapeHtml(a)}</b></button>`).join('')}</div><button class="danger" id="hostWrong" style="margin-top:10px;width:100%">💔 إجابة خاطئة</button></div>`;document.querySelectorAll('.host-solution').forEach(b=>b.onclick=()=>confirm(+b.dataset.i));const cs=$("confirmSuggested");if(cs)cs.onclick=()=>confirm(+cs.dataset.i);const ws=$("wrongSuggested");if(ws)ws.onclick=wrong;$("hostWrong").onclick=wrong;}
function switchActive(s){const o=s.activeTeam==='A'?'B':'A';if((s.hearts?.[o]||0)>0)return o;if((s.hearts?.[s.activeTeam]||0)>0)return s.activeTeam;return s.activeTeam;}
async function confirm(i){const ans=solutions.answers[i];await runTransaction(rr('public/top10'),s=>{if(!s||s.revealed?.[i]!=null)return s;s.revealed=s.revealed||{};s.revealed[i]=ans;s.scores=s.scores||{A:0,B:0};s.scores[s.activeTeam]=(s.scores[s.activeTeam]||0)+(i+1);s.lastMessage=`✅ الحكم أكد المركز ${i+1}`;s.activeTeam=switchActive(s);return s;});await remove(rr('hostPending'));}
async function wrong(){await runTransaction(rr('public/top10'),s=>{if(!s)return s;s.hearts=s.hearts||{A:3,B:3};s.hearts[s.activeTeam]=Math.max(0,(s.hearts[s.activeTeam]||0)-1);s.lastMessage='💔 الحكم رفض الإجابة';s.activeTeam=switchActive(s);return s;});await remove(rr('hostPending'));}
boot().catch(e=>{$("hostStatus").textContent=e.message});
